version: '3.8'

services:
  deploy-target:
    build:
      context: .
      dockerfile: deploy/Dockerfile.local
    container_name: esheet-deploy-target
    ports:
      - '2046:22'
      - '8080:80'
    volumes:
      - esheet-deploy:/home/deploy/esheet
    environment:
      - DEPLOY_USER=deploy
      - DEPLOY_REPO_PATH=/home/deploy/esheet
    networks:
      - esheet-local

volumes:
  esheet-deploy:

networks:
  esheet-local:
    driver: bridge
