server {
  listen 80 default_server;
  listen [::]:80 default_server;
  server_name _;

  root /home/llatt/sites/esheet/current;
  index index.html;

  location /demo/assets/ {
    try_files $uri =404;
    expires 1y;
    add_header Cache-Control "public, immutable";
  }

  location /assets/ {
    try_files $uri =404;
    expires 1y;
    add_header Cache-Control "public, immutable";
  }

  location = /demo/index.html {
    add_header Cache-Control "no-cache, no-store, must-revalidate" always;
    add_header Pragma "no-cache" always;
    add_header Expires "0" always;
  }

  location = /index.html {
    add_header Cache-Control "no-cache, no-store, must-revalidate" always;
    add_header Pragma "no-cache" always;
    add_header Expires "0" always;
  }

  location /demo/ {
    try_files $uri $uri/ /demo/index.html;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }

  location ~ /\.
  {
    deny all;
  }
}
