// @vitest-environment jsdom
import React from 'react';
import { afterEach, beforeEach, expect, it, vi } from 'vitest';
import {
  act,
  cleanup,
  fireEvent,
  render,
  screen,
  waitFor,
} from '@testing-library/react';
import { exportResponse } from '@esheet/adapters';
import { renderResponseHtml } from '@esheet/adapters/html';
import {
  ResponseDocumentPreview,
  responseDocumentLabels as labels,
  type ResponseDocumentSnapshot,
} from './ResponseDocumentPreview.js';

vi.mock('@esheet/adapters', () => ({ exportResponse: vi.fn() }));
vi.mock('@esheet/adapters/html', () => ({ renderResponseHtml: vi.fn() }));

const snapshot: ResponseDocumentSnapshot = {
  form: { id: 'test', title: 'Test form', pages: [] },
  response: { hidden: { answer: 'Preserved' } },
};
const exported = {
  mdy: '---\nresponse: full-data\n---\n# Body',
  markdown: '# Body',
  diagnostics: [{ code: 'unknown-field', fieldId: 'hidden' }],
};
const html = '<!doctype html><html><body><h1>Body</h1></body></html>';
const dialogMethods = Object.getOwnPropertyDescriptors(
  HTMLDialogElement.prototype
);

beforeEach(() => {
  vi.mocked(exportResponse).mockReset().mockResolvedValue(exported);
  vi.mocked(renderResponseHtml).mockReset().mockResolvedValue(html);
  // jsdom does not implement native modal dialog methods.
  Object.defineProperties(HTMLDialogElement.prototype, {
    showModal: {
      configurable: true,
      value(this: HTMLDialogElement) {
        this.setAttribute('open', '');
      },
    },
    close: {
      configurable: true,
      value(this: HTMLDialogElement) {
        this.removeAttribute('open');
      },
    },
  });
  vi.stubGlobal(
    'URL',
    Object.assign(class extends URL {}, {
      createObjectURL: vi.fn(() => 'blob:document'),
      revokeObjectURL: vi.fn(),
    })
  );
});

afterEach(() => {
  cleanup();
  vi.restoreAllMocks();
  vi.unstubAllGlobals();
  for (const method of ['showModal', 'close']) {
    Reflect.deleteProperty(HTMLDialogElement.prototype, method);
    if (dialogMethods[method]) {
      Object.defineProperty(
        HTMLDialogElement.prototype,
        method,
        dialogMethods[method]
      );
    }
  }
  document.documentElement.removeAttribute('lang');
  document.documentElement.removeAttribute('dir');
});

it('uses the full snapshot and host locale, renders an isolated document and prints only that frame', async () => {
  document.documentElement.lang = 'ar';
  document.documentElement.dir = 'rtl';
  const parentPrint = vi.spyOn(window, 'print').mockImplementation(() => {});
  render(<ResponseDocumentPreview snapshot={snapshot} onClose={vi.fn()} />);
  expect(screen.getByText(labels.busy)).toBeTruthy();
  expect(screen.getByText(labels.preservationWarning)).toBeTruthy();
  expect(screen.getByText(labels.completionNotice)).toBeTruthy();
  const frame = (await screen.findByTitle(
    labels.frameTitle
  )) as HTMLIFrameElement;
  expect(exportResponse).toHaveBeenCalledWith(snapshot.form, snapshot.response);
  expect(renderResponseHtml).toHaveBeenCalledWith(exported.markdown, {
    title: 'Test form',
    language: 'ar',
    direction: 'rtl',
  });
  expect(frame.getAttribute('sandbox')).toBe('allow-same-origin allow-modals');
  expect(frame.srcdoc).toBe(html);
  expect(screen.getByText('unknown-field — hidden')).toBeTruthy();
  expect(
    screen.getByText(exported.mdy, { normalizer: (text) => text })
  ).toBeTruthy();
  expect(screen.getByText(exported.markdown)).toBeTruthy();
  const printButton = screen.getByRole('button', { name: labels.print });
  const frameWindow = frame.contentWindow;
  if (!frameWindow) throw new Error('Missing preview window');
  const framePrint = vi
    .spyOn(frameWindow, 'print')
    .mockImplementation(() => {});
  vi.spyOn(frameWindow, 'focus').mockImplementation(() => {});
  fireEvent.load(frame);
  fireEvent.click(printButton);
  expect(framePrint).toHaveBeenCalledOnce();
  expect(parentPrint).not.toHaveBeenCalled();
  expect(renderResponseHtml).toHaveBeenCalledOnce();
});

it('downloads exact generated bytes and revokes every object URL on close', async () => {
  const blobs: Blob[] = [];
  vi.mocked(URL.createObjectURL).mockImplementation((blob) => {
    blobs.push(blob as Blob);
    return `blob:document-${blobs.length}`;
  });
  const names: string[] = [];
  vi.spyOn(HTMLAnchorElement.prototype, 'click').mockImplementation(
    function () {
      names.push(this.download);
    }
  );
  const view = render(
    <ResponseDocumentPreview snapshot={snapshot} onClose={vi.fn()} />
  );
  await screen.findByTitle(labels.frameTitle);
  for (const name of [
    labels.downloadMdy,
    labels.downloadMarkdown,
    labels.downloadHtml,
  ]) {
    fireEvent.click(screen.getByRole('button', { name }));
  }
  expect(names).toEqual(['test.mdy', 'test.md', 'test.html']);
  const texts = await Promise.all(
    blobs.map(
      (blob) =>
        new Promise((resolve) => {
          const reader = new FileReader();
          reader.onload = () => resolve(reader.result);
          reader.readAsText(blob);
        })
    )
  );
  expect(texts).toEqual([exported.mdy, exported.markdown, html]);
  view.unmount();
  expect(URL.revokeObjectURL).toHaveBeenCalledTimes(3);
});

it('discards old async exports when the snapshot changes or the preview closes', async () => {
  let resolveOld!: (value: typeof exported) => void;
  vi.mocked(exportResponse).mockReturnValueOnce(
    new Promise((resolve) => {
      resolveOld = resolve;
    })
  );
  const view = render(
    <ResponseDocumentPreview snapshot={snapshot} onClose={vi.fn()} />
  );
  const next = { ...snapshot, form: { ...snapshot.form, id: 'next' } };
  view.rerender(<ResponseDocumentPreview snapshot={next} onClose={vi.fn()} />);
  await screen.findByTitle(labels.frameTitle);
  await act(async () => resolveOld({ ...exported, markdown: 'Stale' }));
  expect(renderResponseHtml).toHaveBeenCalledTimes(1);
  expect(screen.queryByText('Stale')).toBeNull();
  let resolveHtml!: (value: string) => void;
  vi.mocked(renderResponseHtml).mockReturnValueOnce(
    new Promise((resolve) => {
      resolveHtml = resolve;
    })
  );
  view.rerender(
    <ResponseDocumentPreview snapshot={snapshot} onClose={vi.fn()} />
  );
  await waitFor(() => expect(renderResponseHtml).toHaveBeenCalledTimes(2));
  view.rerender(<ResponseDocumentPreview snapshot={null} onClose={vi.fn()} />);
  await act(async () => resolveHtml('Stale HTML'));
  expect(screen.queryByRole('dialog')).toBeNull();
});

it('announces generation errors, supports translated labels, and restores focus', async () => {
  vi.mocked(exportResponse).mockRejectedValueOnce(new Error('private details'));
  const trigger = document.createElement('button');
  document.body.append(trigger);
  trigger.focus();
  const onClose = vi.fn();
  const view = render(
    <ResponseDocumentPreview
      snapshot={snapshot}
      onClose={onClose}
      labels={{ close: 'Fermer', error: 'Échec' }}
    />
  );
  expect(document.activeElement).toBe(
    screen.getByRole('button', { name: 'Fermer' })
  );
  expect(await screen.findByText('Échec')).toBeTruthy();
  expect(screen.getByRole('alert').textContent).toBe('Échec');
  expect(screen.queryByText('private details')).toBeNull();
  expect(screen.queryByTitle(labels.frameTitle)).toBeNull();
  fireEvent(
    screen.getByRole('dialog'),
    new Event('cancel', { cancelable: true })
  );
  expect(onClose).toHaveBeenCalledOnce();
  view.unmount();
  expect(document.activeElement).toBe(trigger);
  trigger.remove();
});

it('announces HTML generation and print failures without printing the parent', async () => {
  vi.mocked(renderResponseHtml).mockRejectedValueOnce(new Error('bad html'));
  const view = render(
    <ResponseDocumentPreview snapshot={snapshot} onClose={vi.fn()} />
  );
  expect(await screen.findByText(labels.error)).toBeTruthy();
  view.rerender(
    <ResponseDocumentPreview snapshot={{ ...snapshot }} onClose={vi.fn()} />
  );
  const frame = (await screen.findByTitle(
    labels.frameTitle
  )) as HTMLIFrameElement;
  const frameWindow = frame.contentWindow;
  if (!frameWindow) throw new Error('Missing preview window');
  vi.spyOn(frameWindow, 'focus').mockImplementation(() => {});
  vi.spyOn(frameWindow, 'print').mockImplementation(() => {
    throw new Error('blocked');
  });
  fireEvent.load(frame);
  fireEvent.click(screen.getByRole('button', { name: labels.print }));
  expect(screen.getByRole('alert').textContent).toBe(labels.printError);
});
